### ISSUE TITLE
[FEAT] 동아리 만들기 API

### ISSUE THREAD

**Issue by yaeoni** [Crew-Space/crewspace-resource#6]
## 📌 Feature Issue

- 동아리 생성 API 생성
- [기본 생성]
    - 회원 카테고리( 운영진 )
    - 게시글 카테고리( 공지 : 일반 공지 / 커뮤니티 : 일반 )
    - 동아리 생성자 운영진으로서 동아리 자동 가입
    
## 📝 To-do

- [ ] reqeust validation 걸기
- [ ] 회원 카테고리 기본 생성
- [ ] 게시글 카테고리 기본 생성
- [ ] 생성 멤버 운영진 기본 설정
